services:
  mysql-master:
    image: mysql
    container_name: mysql-master
    hostname: mysql-master
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: luis
        MYSQL_PASSWORD: luis
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./volumes/mysql-master:/var/lib/mysql"
      - "./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - ${GLOBAL_NETWORK:-example-network}

volumes:
  db:
    driver: local